apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort    # <- change this from ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30080   # <- must be between 30000-32767 and unused
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
